/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyAbiraRouteImport } from './routes/why-abira'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CelebrityRouteImport } from './routes/celebrity'
import { Route as BrandedRouteImport } from './routes/branded'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductKindIdRouteImport } from './routes/product.$kind.$id'

const WhyAbiraRoute = WhyAbiraRouteImport.update({
  id: '/why-abira',
  path: '/why-abira',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrityRoute = CelebrityRouteImport.update({
  id: '/celebrity',
  path: '/celebrity',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandedRoute = BrandedRouteImport.update({
  id: '/branded',
  path: '/branded',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductKindIdRoute = ProductKindIdRouteImport.update({
  id: '/product/$kind/$id',
  path: '/product/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branded': typeof BrandedRoute
  '/celebrity': typeof CelebrityRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speakers': typeof SpeakersRoute
  '/terms': typeof TermsRoute
  '/why-abira': typeof WhyAbiraRoute
  '/product/$kind/$id': typeof ProductKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branded': typeof BrandedRoute
  '/celebrity': typeof CelebrityRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speakers': typeof SpeakersRoute
  '/terms': typeof TermsRoute
  '/why-abira': typeof WhyAbiraRoute
  '/product/$kind/$id': typeof ProductKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branded': typeof BrandedRoute
  '/celebrity': typeof CelebrityRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speakers': typeof SpeakersRoute
  '/terms': typeof TermsRoute
  '/why-abira': typeof WhyAbiraRoute
  '/product/$kind/$id': typeof ProductKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/branded'
    | '/celebrity'
    | '/collection'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/speakers'
    | '/terms'
    | '/why-abira'
    | '/product/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/branded'
    | '/celebrity'
    | '/collection'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/speakers'
    | '/terms'
    | '/why-abira'
    | '/product/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/branded'
    | '/celebrity'
    | '/collection'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/speakers'
    | '/terms'
    | '/why-abira'
    | '/product/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandedRoute: typeof BrandedRoute
  CelebrityRoute: typeof CelebrityRoute
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeakersRoute: typeof SpeakersRoute
  TermsRoute: typeof TermsRoute
  WhyAbiraRoute: typeof WhyAbiraRoute
  ProductKindIdRoute: typeof ProductKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-abira': {
      id: '/why-abira'
      path: '/why-abira'
      fullPath: '/why-abira'
      preLoaderRoute: typeof WhyAbiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrity': {
      id: '/celebrity'
      path: '/celebrity'
      fullPath: '/celebrity'
      preLoaderRoute: typeof CelebrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branded': {
      id: '/branded'
      path: '/branded'
      fullPath: '/branded'
      preLoaderRoute: typeof BrandedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$kind/$id': {
      id: '/product/$kind/$id'
      path: '/product/$kind/$id'
      fullPath: '/product/$kind/$id'
      preLoaderRoute: typeof ProductKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandedRoute: BrandedRoute,
  CelebrityRoute: CelebrityRoute,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeakersRoute: SpeakersRoute,
  TermsRoute: TermsRoute,
  WhyAbiraRoute: WhyAbiraRoute,
  ProductKindIdRoute: ProductKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
